### ISSUE TITLE
Make attachMediaStream() return rtcninja.attachMediaStream()

### ISSUE THREAD

**Issue by ibc** [AGProjects/sylkrtc.js#1]
In case the Temasys plugin is used, calling `attachMediaStream(element, stream)` will override the given `element` (the  `<video>` element is replaced with a `<object>`) so the new element (the `<object>`) is returned by the function.

https://github.com/AGProjects/sylkrtc.js/blob/master/lib/sylkrtc.js#L27

**Comment by saghul** [comment]
Thanks for the heads up! I'll need to test it out, because I'm not sure how React will react to swiping the element from under its feet. (pun intended)
