### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by webrtcccccc** [AGProjects/sylkrtc.js#2]
ubuntupc@ubuntupc-ml:~/sylkrtc.js$ sudo ./configure
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! code 1
npm ERR! Command failed: git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntupc/.npm/_logs/2019-08-15T05_30_56_242Z-debug.log
ubuntupc@ubuntupc-ml:~/sylkrtc.js$

**Comment by saghul** [comment]
Looks like Gulp 4 got finally released and the branch got removed from upstream. This can just depend on Gulp 4.0.2 (latest as of today) I guess. /cc @tijmenNL

**Comment by tijmenNL** [comment]
You're right. I bumped the version. A commit will land shortly which fixes the issue.
